version: 2
jobs:
  build:
    working_directory: ~/Android/Workspace/anabeesh-android

    docker:
      - image: circleci/android:api-25-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "amaanuser/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "snap_car/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew clean
          command: ./gradlew build
          command: ./gradlew check
          command: ./gradlew test
      - store_artifacts:
          path: amaanuser/build/reports/
          destination: reports
      - store_test_results:
          path: amaanuser/build/reports/test_results